### ISSUE TITLE
Deployment Environment

### ISSUE THREAD

**Issue by AppFolioRopes** [AppFolioOnboarding/image-sharer-KyCodeHuynh#1]
#### As a developer I want a continuous deployment environment setup for my new Rails application.

Acceptance criteria:
- [x] [GitHub](https://github.com/AppFolioOnboarding) is used for source
  control.
- [x] The project's version of both Ruby and Rails are used both locally and on
  Heroku.
- [x] The landing page, `/`, provides some content.
- [x] Every available controller action has corresponding tests.
- [x] [CircleCI](https://circleci.com/) is used for Continuous Integration.
- [x] Heroku is used to deploy the application.
- [x] Pull requests are automatically deployed as review applications.
- [x] The staging application automatically deploys whenever the master branch
  is updated.
- [x] The staging application automatically deploys only after all tests pass
  on CircleCI.
- [x] The staging application deployment can be promoted to the production
  application deployment.
- [x] [Pronto](https://github.com/mmozuras/pronto) is used to help with code
  style consistency.

Discussion Topics:
- [x] Where can we discover how long it takes to return an HTTP response?
- [x] When should we commit our code?

References:
* https://rvm.io/rvm/install#try-out-your-new-rvm-installation
* http://guides.rubyonrails.org/getting_started.html
* http://guides.rubyonrails.org/testing.html#functional-tests-for-your-controllers
* https://devcenter.heroku.com/articles/getting-started-with-rails4
* https://devcenter.heroku.com/articles/pipelines
* https://github.com/bbatsov/ruby-style-guide

**Comment by KyCodeHuynh** [comment]
> Where can we discover how long it takes to return an HTTP response?

This is shown in the Rails logs: "rendered view in so-and-so ms".

> When should we commit our code?

After tests have been written; they should be included in the commit (which may require squashing locally).

**Comment by KyCodeHuynh** [comment]
>  Pronto is used to help with code style consistency.

An alternative is to use the [RuboCop](https://packagecontrol.io/packages/RuboCop) package within Sublime.

**Comment by KyCodeHuynh** [comment]
Following a quick self-QA check on [staging](https://image-sharer-kycodehuynh-stagi.herokuapp.com/), this is now live on [production](https://image-sharer-kycodehuynh-produ.herokuapp.com/).
