### ISSUE TITLE
Save Image Link

### ISSUE THREAD

**Issue by AppFolioRopes** [AppFolioOnboarding/image-sharer-KyCodeHuynh#2]
#### As a user I want to save a link to an image.

Acceptance criteria:
- [x] The link is entered through a form.
- [x] After the form is saved, the link is persisted in the database.

Dependencies:
- Deployment Environment

__Note__: Many image sharing sites will permit one to upload images, or
download images when provided a link. For this project we will only work with
the link, i.e., URL, to various images.

**Comment by KyCodeHuynh** [comment]
Look for the new image-link page [here](http://localhost:3000/images/new). I'm steadily fleshing it out.

**Comment by KyCodeHuynh** [comment]
Daniel (Vicory) mentioned [Simple Forms](https://github.com/plataformatec/simple_form), which looks like a really useful gem.
