### ISSUE TITLE
Image Index

### ISSUE THREAD

**Issue by AppFolioRopes** [AppFolioOnboarding/image-sharer-KyCodeHuynh#3]
#### As a user I want the homepage to display all saved images.

Acceptance criteria:
- [x] New images that are added show up on the homepage.
- [x] These images are persisted if the browser is closed or even if the
  server is restarted.
- [x] Images are not displayed wider than 400px.

Dependencies:
- Save Image Link

**Comment by KyCodeHuynh** [comment]
Architectural decision: Rather than creating a `ImageLinksController#index` action (at least for now), I'll instead have `HomeController` talk to the `ImageLink` model.

**Comment by KyCodeHuynh** [comment]
> These images are persisted if the browser is closed or even if the server is restarted. 

The images are simply URLs stored in the database, then hot-linked on the homepage and will not disappear unless the original image source does. However, such image-linking breaks if the original image is moved or deleted. 

If we wanted more robust persistence, something like the [Paperclip gem](https://github.com/thoughtbot/paperclip) would be needed to store the downloaded images locally or on S3, etc.

**Comment by KyCodeHuynh** [comment]
Waiting on feedback from @bboe on whether the intention was to store images in some way, or to just hot-link to them using stored image ​_links_​.

**Comment by KyCodeHuynh** [comment]
Waiting on feedback from @bboe on whether the intention was to store images in some way, or to just hot-link to them using stored image ​_links_​.

**Comment by KyCodeHuynh** [comment]
Clarification received: hot-linking with stored links is fine.
