### ISSUE TITLE
Image Seeds

### ISSUE THREAD

**Issue by AppFolioRopes** [AppFolioOnboarding/image-sharer-KyCodeHuynh#5]
#### As a developer I want at least 20 images to be created when I setup the database.

Acceptance criteria:
- [ ] After running `rake db:setup` at least 20 images are shown in the
  homepage.
- [ ] When a new app is deployed on heroku (e.g., every review app), that app
  has at least 20 images on its homepage.

Dependencies:
- Image Index

**Comment by KyCodeHuynh** [comment]
Technically, the above does not call for 20 _unique_ images, so I repeat 5 images from [Unsplash](https://unsplash.com/) instead. 

Note also the difference between [fixtures and seeds](https://stackoverflow.com/questions/29138077/rails-fixtures-vs-seeds) in Rails. Fixtures are data for testing, and do not persist between tests. Seed data, however, is whatever is required for an app to function (like ZIP codes for a delivery tracker with embedded map), or in our case, have a non-empty (and therefore non-sad) front page.
