### ISSUE TITLE
Delete Image

### ISSUE THREAD

**Issue by AppFolioRopes** [AppFolioOnboarding/image-sharer-KyCodeHuynh#8]
#### As a user I want to delete an image.

Acceptance criteria:
- [ ] The user is prompted for confirmation prior to deletion.
- [ ] Deleted images are removed from the homepage.

Dependencies:
- Image Index

**Comment by D-D-M** [comment]
Am I supposed to do something with this?

**Comment by KyCodeHuynh** [comment]
Hi, @D-D-M, no you are not. :-)

I'm not sure why you're listed as a participant here. @ipmsteven is handling the code review.
